from typing import Any

class AudioProcessor:
    def __init__(self, config: dict[str, float | int], sample_rate: float = ...) -> None: ...
    def feed_samples(self, samples: Any) -> None: ...
    def frame(self) -> dict[str, Any]: ...
    def features(self) -> dict[str, Any]: ...
    def state_copy(self) -> AudioProcessor: ...
    def reset(self) -> None: ...
    def normalization_gain(self) -> float: ...
    def stats(self) -> dict[str, Any]: ...
