"""Stable LumiStripe primitives and playback orchestration.

Concrete animation/effect classes, native hardware backends, and live audio
capture are intentionally lazy integrations.  Import those from ``animation``,
``effects``, ``gpio``, and ``audio`` respectively.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any

from .buffers import (
    PixelBuffer,
    apply_brightness_rgb,
    clear,
    fade,
    fill_rgb,
    new_pixel_buffer,
)
from .color import Color, ColorBatch, Hex, Hsl, Hsla, Rgb, Rgba
from .controller import (
    BrightnessController,
    ColorCorrection,
    ColorCorrectionController,
    CompositeController,
    Controller,
    DualController,
    MultiController,
    NullController,
    ReversedController,
    ScaledMultiController,
)
from .playback import (
    AudioSource,
    CycleOrder,
    CycleTiming,
    CyclingConfig,
    MusicActivityConfig,
    MusicActivityDetector,
    MusicGateState,
    PlaybackConfig,
    PlaybackDecision,
    PlaybackEngine,
    PlaybackMode,
    ReactiveFrameSmoother,
    RenderPlan,
    build_render_plan,
    decide_playback,
    demo_snapshot,
)
from .power import (
    OutputPowerEstimate,
    PowerBudgetResult,
    apply_power_budget,
    estimate_frame_power,
)
from .stripe import Config, Stripe, SubStripe

_LAZY_EXPORTS: dict[str, tuple[str, str]] = {
    # Audio value objects stay convenient, while device/capture integrations
    # are loaded only when explicitly requested.
    "AudioAnalysis": ("lumistripe.audio.config", "AudioAnalysis"),
    "AudioCalibrationResult": ("lumistripe.audio.types", "AudioCalibrationResult"),
    "AudioConfig": ("lumistripe.audio.config", "AudioConfig"),
    "AudioFeatures": ("lumistripe.audio.types", "AudioFeatures"),
    "AudioFrame": ("lumistripe.audio.types", "AudioFrame"),
    "AudioInput": ("lumistripe.audio.capture", "AudioInput"),
    "AudioInputDevice": ("lumistripe.audio.types", "AudioInputDevice"),
    "AudioInputHealth": ("lumistripe.audio.types", "AudioInputHealth"),
    "AudioNormalization": ("lumistripe.audio.config", "AudioNormalization"),
    "AudioProcessorStats": ("lumistripe.audio.types", "AudioProcessorStats"),
    "AudioSmoothing": ("lumistripe.audio.config", "AudioSmoothing"),
    "AudioSnapshot": ("lumistripe.audio.types", "AudioSnapshot"),
    "AudioState": ("lumistripe.audio.dsp", "AudioState"),
    "HardwareGainController": ("lumistripe.audio.hardware_gain", "HardwareGainController"),
    "HardwareGainStatus": ("lumistripe.audio.hardware_gain", "HardwareGainStatus"),
    "MusicFeatures": ("lumistripe.audio.types", "MusicFeatures"),
    "calibrate_audio_input": ("lumistripe.audio.calibration", "calibrate_audio_input"),
    "features_from_frame": ("lumistripe.audio.dsp", "features_from_frame"),
    "list_input_device_details": ("lumistripe.audio.devices", "list_input_device_details"),
    "list_input_devices": ("lumistripe.audio.devices", "list_input_devices"),
    "recommend_audio_calibration": ("lumistripe.audio.calibration", "recommend_audio_calibration"),
    # Animation catalog and concrete implementations.
    "Animation": ("lumistripe.animation.base", "Animation"),
    "AnimationDefinition": ("lumistripe.animation.catalog", "AnimationDefinition"),
    "AnimationMetadata": ("lumistripe.selector.metadata", "AnimationMetadata"),
    "AnimationPlayer": ("lumistripe.animation.base", "AnimationPlayer"),
    "AnimationRole": ("lumistripe.selector.metadata", "AnimationRole"),
    "AnimationScore": ("lumistripe.selector.scoring", "AnimationScore"),
    "AnimationScoringEngine": ("lumistripe.selector.scoring", "AnimationScoringEngine"),
    "DynamicSelector": ("lumistripe.selector.dynamic", "DynamicSelector"),
    "DynamicSelectorConfig": ("lumistripe.selector.scoring", "DynamicSelectorConfig"),
    "DynamicSelectorDiagnostics": ("lumistripe.selector.dynamic", "DynamicSelectorDiagnostics"),
    "SelectorDecision": ("lumistripe.selector.dynamic", "SelectorDecision"),
    "animation_catalog": ("lumistripe.animation.catalog", "animation_catalog"),
    "party_catalog": ("lumistripe.animation.catalog", "party_catalog"),
    "animation_metadata": ("lumistripe.selector.metadata", "animation_metadata"),
    "Aurora": ("lumistripe.animation.aurora", "Aurora"),
    "BouncingBall": ("lumistripe.animation.bouncing_ball", "BouncingBall"),
    "Bpm": ("lumistripe.animation.bpm", "Bpm"),
    "ColorWipe": ("lumistripe.animation.color_wipe", "ColorWipe"),
    "Comet": ("lumistripe.animation.comet", "Comet"),
    "CometStorm": ("lumistripe.animation.comet_storm", "CometStorm"),
    "DanceFloor": ("lumistripe.animation.dance_floor", "DanceFloor"),
    "DiscoComet": ("lumistripe.animation.disco_comet", "DiscoComet"),
    "DiscoSparkle": ("lumistripe.animation.disco_sparkle", "DiscoSparkle"),
    "DualComet": ("lumistripe.animation.dual_comet", "DualComet"),
    "DualLaser": ("lumistripe.animation.dual_laser", "DualLaser"),
    "Fire": ("lumistripe.animation.fire", "Fire"),
    "GlowRush": ("lumistripe.animation.glow_rush", "GlowRush"),
    "Juggle": ("lumistripe.animation.juggle", "Juggle"),
    "LaserSweep": ("lumistripe.animation.laser_sweep", "LaserSweep"),
    "NeonConfetti": ("lumistripe.animation.neon_confetti", "NeonConfetti"),
    "NeonStorm": ("lumistripe.animation.neon_storm", "NeonStorm"),
    "PeakMirror": ("lumistripe.animation.peak_mirror", "PeakMirror"),
    "PlasmaRave": ("lumistripe.animation.plasma_rave", "PlasmaRave"),
    "Police": ("lumistripe.animation.police", "Police"),
    "Pulse": ("lumistripe.animation.pulse", "Pulse"),
    "Rainbow": ("lumistripe.animation.rainbow", "Rainbow"),
    "RainbowCycle": ("lumistripe.animation.rainbow_cycle", "RainbowCycle"),
    "RainbowStrobe": ("lumistripe.animation.rainbow_strobe", "RainbowStrobe"),
    "RavePulse": ("lumistripe.animation.rave_pulse", "RavePulse"),
    "RaveScanner": ("lumistripe.animation.rave_scanner", "RaveScanner"),
    "RedBlackoutStrobe": ("lumistripe.animation.red_rave", "RedBlackoutStrobe"),
    "RedRaveChase": ("lumistripe.animation.red_rave", "RedRaveChase"),
    "RedRaveSweep": ("lumistripe.animation.red_rave", "RedRaveSweep"),
    "RgbwTest": ("lumistripe.animation.rgbw_test", "RgbwTest"),
    "Sinelon": ("lumistripe.animation.sinelon", "Sinelon"),
    "Strobe": ("lumistripe.animation.strobe", "Strobe"),
    "StrobeChase": ("lumistripe.animation.strobe_chase", "StrobeChase"),
    "TheaterChase": ("lumistripe.animation.theater_chase", "TheaterChase"),
    "Twinkle": ("lumistripe.animation.twinkle", "Twinkle"),
    "Wave": ("lumistripe.animation.wave", "Wave"),
    # Effects are an explicit integration surface.
    "BassDrop": ("lumistripe.effects.bass_drop", "BassDrop"),
    "BeatExplosion": ("lumistripe.effects.beat_explosion", "BeatExplosion"),
    "BeatRipple": ("lumistripe.effects.beat_ripple", "BeatRipple"),
    "BeatTunnel": ("lumistripe.effects.beat_tunnel", "BeatTunnel"),
    "BeatWave": ("lumistripe.effects.beat_wave", "BeatWave"),
    "BlendMode": ("lumistripe.effects.layers", "BlendMode"),
    "CenterBurst": ("lumistripe.effects.center_burst", "CenterBurst"),
    "ClubFlash": ("lumistripe.effects.club_flash", "ClubFlash"),
    "ColorBurst": ("lumistripe.effects.color_burst", "ColorBurst"),
    "Confetti": ("lumistripe.effects.confetti", "Confetti"),
    "DropExplosion": ("lumistripe.effects.drop_explosion", "DropExplosion"),
    "DropWave": ("lumistripe.effects.drop_wave", "DropWave"),
    "ElectricStorm": ("lumistripe.effects.electric_storm", "ElectricStorm"),
    "FireworkBurst": ("lumistripe.effects.firework_burst", "FireworkBurst"),
    "HardBeat": ("lumistripe.effects.hard_beat", "HardBeat"),
    "LightningStrike": ("lumistripe.effects.lightning_strike", "LightningStrike"),
    "MirrorFlash": ("lumistripe.effects.mirror_flash", "MirrorFlash"),
    "PixelExplosion": ("lumistripe.effects.pixel_explosion", "PixelExplosion"),
    "Shockwave": ("lumistripe.effects.shockwave", "Shockwave"),
    "SpectrumFlash": ("lumistripe.effects.spectrum_flash", "SpectrumFlash"),
    "Effect": ("lumistripe.effects.base", "Effect"),
    "EffectCategory": ("lumistripe.effects.layers", "EffectCategory"),
    "EffectDefinition": ("lumistripe.effects.layers", "EffectDefinition"),
    "EffectLayerStatus": ("lumistripe.effects.layers", "EffectLayerStatus"),
    "EffectScheduler": ("lumistripe.effects.layers", "EffectScheduler"),
    "EffectSchedulerConfig": ("lumistripe.effects.layers", "EffectSchedulerConfig"),
    "EffectSchedulerDiagnostics": ("lumistripe.effects.layers", "EffectSchedulerDiagnostics"),
    "EffectTriggerResult": ("lumistripe.effects.layers", "EffectTriggerResult"),
    "EffectTriggerStatus": ("lumistripe.effects.layers", "EffectTriggerStatus"),
    "LayeredRenderer": ("lumistripe.effects.layers", "LayeredRenderer"),
    # Optional output and persisted microphone profile integrations.
    "GPIOStripe": ("lumistripe.gpio", "GPIOStripe"),
    "SPIConfig": ("lumistripe.gpio.spi", "SPIConfig"),
    "SPIStripe": ("lumistripe.gpio.spi", "SPIStripe"),
    "BUILTIN_MIC_PROFILES": ("lumistripe.mic_profile", "BUILTIN_MIC_PROFILES"),
    "PCM2902_PROFILE": ("lumistripe.mic_profile", "PCM2902_PROFILE"),
    "MicProfile": ("lumistripe.mic_profile", "MicProfile"),
    "load_mic_profile": ("lumistripe.mic_profile", "load_mic_profile"),
    "match_builtin_mic_profile": ("lumistripe.mic_profile", "match_builtin_mic_profile"),
    "mic_profile_from_dict": ("lumistripe.mic_profile", "mic_profile_from_dict"),
    "write_mic_profile": ("lumistripe.mic_profile", "write_mic_profile"),
}


def __getattr__(name: str) -> Any:
    target = _LAZY_EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attribute_name = target
    value = getattr(import_module(module_name), attribute_name)
    globals()[name] = value
    return value


__all__ = [
    "AudioSource",
    "BrightnessController",
    "Color",
    "ColorBatch",
    "ColorCorrection",
    "ColorCorrectionController",
    "CompositeController",
    "Config",
    "Controller",
    "CycleOrder",
    "CycleTiming",
    "CyclingConfig",
    "DualController",
    "Hex",
    "Hsl",
    "Hsla",
    "MultiController",
    "MusicActivityConfig",
    "MusicActivityDetector",
    "MusicGateState",
    "NullController",
    "OutputPowerEstimate",
    "PixelBuffer",
    "PlaybackConfig",
    "PlaybackDecision",
    "PlaybackEngine",
    "PlaybackMode",
    "PowerBudgetResult",
    "ReactiveFrameSmoother",
    "RenderPlan",
    "ReversedController",
    "Rgb",
    "Rgba",
    "ScaledMultiController",
    "Stripe",
    "SubStripe",
    "apply_brightness_rgb",
    "apply_power_budget",
    "build_render_plan",
    "clear",
    "decide_playback",
    "demo_snapshot",
    "estimate_frame_power",
    "fade",
    "fill_rgb",
    "new_pixel_buffer",
]
