from typing import Any

class GPIOMem:
    def __init__(self, data_pin: int, clock_pin: int) -> None: ...
    def set_values(self, data: bool, clock: bool) -> None: ...
    def flush(self, pixels: Any) -> None: ...
    def close(self) -> None: ...
